### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by riodda** [ATM-HSW/mbed_target#1]
I've tried to install (executing the .m) but i have this error message

Error in setup_MbedTarget (line 36)
mbed.Prefs.setMbedTarget('DISCO_F407VG');

**Comment by ohagendorf** [comment]
Did you use the release zip file download? Or did you clone/download the master branch?

The release zip version is the preferable way, because the mbed subproject is included, mex files are compiled and also the help system is compiled.

The mentioned line can be removed. It is not longer necessary and in the current working branch master1 already removed.

**Comment by riodda** [comment]
I download the master branch, will try again with the release zip, thanks for pointing out.

**Comment by ohagendorf** [comment]
I'll change the first part of the readme soon.
Something like 'first steps' should be at the first beginning of the readme.

**Comment by riodda** [comment]
Yes installations steps for nebiews (like me) would be very usefould, i had to comment the lines from 36 to 47, now the script don't find the arm compiler but i've just installed it and it should be in path...

**Comment by ohagendorf** [comment]
Some installation documentation exists. 
But in the master branch it is included only as uncompiled markup ascii text. 
In the release zip this documentation is compiled into html files. You can find installtion, first steps and so on in the htmlhelp subfolder after unzipping release 1 zip file.

**Comment by riodda** [comment]
Thanks will have a look.

**Comment by riodda** [comment]
Can ia ask you a tip ? I have a simulink project that will have to run on one microcontroller board and i have to add to it data imputs trough canbus, what is the mbed platform that will work the best (easier to implement) ? I was aiming to some STM32F4 but i don't want to waste time on it if is not the right platform, in know STM32 can implemtation in MBED have never been great....

**Comment by ohagendorf** [comment]
We did some CAN staff under mbed with F446, F746 and F767.

We realized one project with F767. CAN is used very intensivly there. But it is programmed based on the Cube libraries.

There exists CAN Simulink block in the MbedTarget. But they are not used very intensivly/in only a few student projects. So, I'm sure they can be improved.

**Comment by riodda** [comment]
Cube Libraries for Simulink ?

**Comment by ohagendorf** [comment]
No, plain C.

**Comment by riodda** [comment]
I have sucefoully run the .m script (it was just a path issue in matlab), i've tryed to compile one of the examples (the can receive) but i have one error

`### Processing Template Makefile: C:\mbed_target\mbed\mbed.tmf
### Creating CANreceive.mk from C:\mbed_target\mbed\mbed.tmf
### Building CANreceive: .\CANreceive.bat
 
C:\mbed_target\CANreceive_slprj>set MATLAB=C:\Program Files\MATLAB\R2017b  
        1 file copiati. 
"make.exe" non è riconosciuto come comando interno o esterno, 
 un programma eseguibile o un file batch.
### Build procedure for model: 'CANreceive' aborted due to an error.(error)
Error(s) encountered while building "CANreceive"`

Translating from italian it does not find the make.exe 
but i have gnu make in path
C:\Program Files (x86)\GnuWin32\bin

**Comment by ATM-HSW** [comment]
In the targets subfolder under mbed_target you can find a subfolder, with a name combined of the model name, the target name and '_slprj'. In this subfolder you can find a batch file: 'model name.bat'. Among others there is the command to call make.exe

Because the Eclipse binutils are integrated you should not need an external make. But please check the paths in the batch file.

**Comment by riodda** [comment]
This is the batch file:
`set MATLAB=C:\Program Files\MATLAB\R2017b
@echo off & copy "C:\mbed_target\CANreceive_slprj\CANreceive.mk" "C:\mbed_target\CANreceive_slprj\Makefile" & make.exe`

If i invoke make manually from the folder i have a succefull build, after a reboot now seems to compile sucessfoully

**Comment by ATM-HSW** [comment]
Sorry, I mixed it with the current version.

For v1 you need to have make.exe in the PATH. To check if everything is OK, call the setup m-file. It will give you an error message, that make.exe could not be found. Or call the above batch file. It is generated and called during the Simulink model build process resulting in the bin file to flash the microcrontroller.

**Comment by riodda** [comment]
Many thanks, it just just a path problem, just needed to reboot ! I have a further question, were are set the mapping between the hw pins of the micro and the various functions ?

**Comment by ATM-HSW** [comment]
In the Simulnik blocks you can choose a pin name like PA_4. Currently only this naming scheme is supported, all other are in preparation. 

Some blocks like LED or user button are using the Mbed defines e.g. LED1 or USER_BUTTON. When you go to the Mbed platform page of one of the STM targets they put links to peripheralpins.c and pinnames.h files. These are the STM files for all pin mappings.

**Comment by riodda** [comment]
Got it, thanks !

**Comment by ohagendorf** [comment]
That is great.

Could you close this issue, please?

**Comment by riodda** [comment]
Yes, of course can close
